### ISSUE TITLE
Poor Bluetooth Performance

### ISSUE THREAD

**Issue by dsem** [jmontleon/pixelbook-fedora#16] opened 2022-01-14 21:43 UTC
I experience poor bluetooth performance for both mouse and headphone connections.

### Mouse
The mouse is very laggy, though sometimes the lag is more extreme than others. [This is reported](https://www.reddit.com/r/linuxquestions/comments/bc15f8/bluetooth_mouse_is_laggy_very_limited_pollrate/ez3ufhs/) by users of other distributions as well. The solution appears to be to edit bluetooth settings in `/var/lib/bluetooth/<device id>/<peripheral id>/info` to change the latency to 0. I have tried this, but on Fedora [the changes seem to not persist](https://unix.stackexchange.com/q/685971/34796). They revert after only a few seconds and I cannot tell if changing it to zero makes a difference.

I am using a Logitech MX Anywhere S2 mouse, and other reports of laggy mouses also appear to be using logitech MX varieties.

### Headphones

Listening to audio over bluetooth headphones is significantly degraded. The audio sounds distorted, as if the bitrate is changing to various low-bit transfers. I can only stomach it for a little bit, but moving the bluetooth mouse seems to correlate with the audio dropping to lower bitrates (or cutting off completely).

---
I appreciate the work that @jmontleon has done to get this laptop working this well. Please let me know what other info I can provide to assist debugging.

**Comment by jmontleon** [comment] 2022-01-17 21:17
Do you know if you're using A2DP or HFP/HSP?

**Comment by dsem** [comment] 2022-01-22 19:23
Sorry for the delay. I've been able to verify I'm using the A2DP profile. I am not sure if it's related, but I often cannot route audio output to the headphones after establishing the bluetooth connection. It simply does not show up as an available "Output Device" in the sound settings: 
![image](https://user-images.githubusercontent.com/2773346/150652708-1ccabb15-a96d-4653-aa09-fe594b2ffbc4.png)

**Comment by jmontleon** [comment] 2022-01-26 15:15
I was able to test briefly with one set of bluetooth headphones and I couldn't reproduce any issues. I do see HDMI 2 get picked up when I disconnect, which is annoying. I should probably see if I can give the speakers higher priority.

When I have a moment I'll dig out an older set and give them a try.

The only other difference I can think is that I've been prepping and using 5.16 kernels from
https://copr.fedorainfracloud.org/coprs/jmontleon/pixelbook-test/

I suppose it's possible something in the new kernel is performing better. Might be worth a test if you're feeling a little brave.

**Comment by huang-jy** [comment] 2022-02-01 13:49
I use Bluetooth headphones constantly during the day with this setup, and I have no issues at all, other than sometimes the BT connection drops when my system load gets high.

![image](https://user-images.githubusercontent.com/2756283/151980217-46a50fb1-fec1-4ace-9f43-a1d9b57aa1d7.png)

**Comment by dsem** [comment] 2022-02-05 11:17
Thanks for checking! I tried with a different pair of headphones and had much better results.  Must be something specific with the one pair (Beoplay H9) and the bluez stack.

Do either of you use bluetooth mice and have you noticed any mouse lag?

**Comment by huang-jy** [comment] 2022-02-05 12:20
I did. I used a Microsoft Bluetooth Keyboard and mouse without issue. Though with that, the keyboard and mouse disconnect to save battery so when you start typing or move the mouse, there's a pause as the device tries to reconnect on BT, and then the movement/keypress shows up. Other than that, no issues with BT there either. Now I use a Logitech wireless which has a dongle. That lags but only when I plug it in via a 4-in-1 hub. If I plug the dongle directly into the USB-C port or via a USB-C-to-USB converter, it is fine.

**Comment by jmontleon** [comment] 2022-02-07 12:21
Any chance you've seen improvements after updating to one of the 5.16 kernels?

**Comment by dsem** [comment] 2022-02-09 10:26
Yes, the bluetooth mouse works much better with the 5.16 kernel.  It's not perfect, but it's much more usable now.

**Comment by jmontleon** [comment] 2022-02-09 14:06
Glad to hear it. I'll leave this up so it's easier to find. Maybe someone with similar hardware who has had similar issues will see it and can explain how to improve it further. Likewise if you learn anything please feel free to update it here. We can also add improvements to the instructions and/or ansible playbook.

**Comment by jmontleon** [comment] 2022-04-09 03:48
It's probably a bit of a long shot, but I wonder if the aer package / service will help here:
https://github.com/jmontleon/pixelbook-fedora#excessive-aer-logging

**Comment by jmontleon** [comment] 2022-04-21 00:05
Between the above, kernel 5.17, and MrChromebox firmware 4.16 I'd be interested to know if there is any improvement.

**Comment by fp-dsem** [comment] 2022-04-22 14:33
Thank you for following-up. I am seeing normal bluetooth mouse behavior. I did not install the `pixelbook-aer` package and am on kernel 5.16. I don't believe I updated MrChromebox firmware (unless those are delivered via a `dnf update`).

I'm not sure when the improvements happened because I had not bothered using a bluetooth mouse for several months but the experience is completely normal now.

**Comment by jmontleon** [comment] 2022-04-22 15:13
Awesome! Glad to hear it. I'll close this, but feel free to reopen if it misbehaves. I'm stopping builds of kernels as the Fedora kernels are pretty much in shape to take over, but would still be worth investigating if its misbehaving.

**Closed** 2022-04-22 15:14 UTC

**Comment by jmontleon** [comment] 2022-04-22 15:58
From 5.17.5 forward you should just pick up standard Fedora kernels. There's no action to take. The only reason you've picked up the kernels from the copr repo is because I've always bumped the release by one and been very proactive about building before new Fedora kernels hit stable. 

Doing one of the things here will be important for a smooth transition:
https://github.com/jmontleon/pixelbook-fedora/issues/26

If you are or start seeing mouse issues on reboot after the firmware update I've added a service that masks the problem. I don't think it's new to the new firmware. People have long complained about seeing it. 4.16 has made it a lot worse for me it seems.
https://github.com/jmontleon/pixelbook-fedora#touchpad

I'm honestly not sure where the problem with this lies. I've asked for some help trying to get to the bottom of it. 
https://github.com/MrChromebox/firmware/issues/344
